### PR TITLE
Fix nested comments ...

### LINKED ISSUE #31: Nested block comments not supported
Scala supports nested block comments but not the syntax highlighter.

Screenshot from 2019-06-05 14-53-18

### PR DESCRIPTION
**Pull request by PanAeon**
…make links highlighted in the scaladoc, add \@constructor keyword, remove dead code, add snap tests for comments.
fixes #31

### CODE REVIEW

**Comment by olafurpg** [comment]
The CI is failing with a manual unit test
Screenshot 2019-06-25 at 09 17 26

**Comment by PanAeon** [comment]
Sorry, I didn't commit the modified snap file the first time. 
As for the fix I just "recursively" reference the `comments` rule from inside of the block  and scaladoc comments. When the blocks are balanced this works just fine, even across multiple lines. If nested blocks are not balanced everything breaks, but this is also a syntax error in scala.

**Comment by olafurpg** [comment]
Aah, makes sense. Thanks for the explanation. Should we cut a new release with this fix?

**Comment by PanAeon** [comment]
I'll push a fix for #30 shortly, it is really tiny.

**Pull request merged**
