### PR TITLE
Convert syntax file to Typescript

### LINKED ISSUE #15: Use another format for tmLanguage
Can we use something different then `tmLangage` ?

The xml syntax makes it super hard to read, and prevents me personally to make any contributions. 

The file format is very simple, so we can use `CSON`, `YAML`, `typescript`, `scala` ... as a source language, that would be compiled by some very simple pipeline to the `tmLanguage` file, or event better to the `tmLanguage.json` file (which can be validated against json schema).

I think the chosen format should support at least comments and string interpolation, without string interpolation complex regexes become super tangled. Also we can use plain yaml as template and interpolate variables with a preprocessor (but native support is better).

See [dhall-tmlanguage.ts](https://github.com/PanAeon/vscode-language-dhall/blob/master/src/typescript/dhall-tmlanguage.ts) for imperfect example of what I mean.

Of course I can do it locally and contribute the resulting `tmLanguage` file, but then I risk getting superficial changes because I can't guarantee the exact order of fields in the file.

### PR DESCRIPTION
**Pull request by PanAeon**
Fixes #15 
I have converted the original PLIST file with plutil to Json and then used it practically verbatim in typescript. Also I have added validation against the tmLanguage json schema from which the typescript interfaces were also generated.

I have checked the ouptut `tmLanguage.json` file, and it is identical to the original (plutil converted) json.

One note is that I have added output file to the gitignore, but that means if the project hasn't been built then it is possible to package extension without the output file! `vsce package` doesn't throw any errors when file is missing, not sure if the publish process will account for this. Not sure how this can be avoided, except commiting generated file which is a bit lame.

### CODE REVIEW

**Comment by PanAeon** [comment]
I have converted the resulting json syntax back to plist format with `plutil -convert xml1 Scala.tmLanguage.json -o Scala.tmLanguage`. [Diff](https://www.diffnow.com/report/0z8ht). It looks identical, except one field is reordered and I have added a json schema just in case.
Of course I've also run the extension to verify that it works (by packaging it and installing local version), but you (or someone else) might want to do the same to cross-check.

Also I've added pre-install and pre-package scripts and actively chicking that generated file is in place before packaging the extension.

**Comment by smarter** [comment]
Wait, github relies on this repository having a .tmLanguage file to provide syntax highlighting for Scala on github.com (https://github.com/github/linguist/tree/master/vendor). Generating the file from a better format is great but the output still needs to be committed.

**Comment by smarter** [comment]
Hmm, it seems that JSON grammars might also be accepted, but I have no idea how to test if the one added here is going to be correctly interpreted by linguist.

**Comment by PanAeon** [comment]
I can investigate this tomorrow. There're definitely node modules that can
generate plist (tmLanguage) files.

**Comment by smarter** [comment]
Apparently json can work but it has to be in a folder called grammars or syntaxes: https://github.com/github/linguist/blob/9116c90fcbb82ac03b4b33c58cfbde1fcf745e99/tools/grammars/compiler/loader.go#L125

**Comment by smarter** [comment]
One way to find out for sure would be to make a PR against linguist updating the vscode-scala-syntax submodule to the latest commit on master.

**Comment by olafurpg** [comment]
I opened https://github.com/scala/vscode-scala-syntax/pull/23 to unignore the Scala.tmLanguage.json file

**Comment by PanAeon** [comment]
@smarter ,
on the linguist contributing page there're some instruction which I believe can help checking it locally. But I apologise, I just can't make it run on my work macbook. Apparently I have to reinstall the whole system)

**Pull request merged**
