### PR TITLE
Remove extensionKind so that other extensions can depend on scala-syntax via SSH/WSL2

### PR DESCRIPTION
**Pull request by tgodzik**
Based on feedback in https://github.com/microsoft/vscode/issues/128375#issuecomment-878096917

### CODE REVIEW

**Comment by MaximeKjaer** [comment]
Just to make sure I understand the problem correctly: Metals runs on the remote machine, and needs this extension in the remote workspace as well. And currently, since `extensionKind` doesn't contain `workspace`, this extension isn't available on the remote machine. Is that correct?

In either case, this change seems okay to me. A bit of history around this field:

- #199 requested support for web extensions
- In #200, I [said we probably shouldn't set `workspace`](https://github.com/scala/vscode-scala-syntax/pull/200#discussion_r613106831), because I thought that it would be better to run highlighting locally -- but I didn't consider other extensions that might depend on this one.
- The fix in #200 ended up not working, because [web extensions were not stable and fully documented yet](https://github.com/scala/vscode-scala-syntax/pull/200#issuecomment-819620306)

**Comment by tgodzik** [comment]
> Just to make sure I understand the problem correctly: Metals runs on the remote machine, and needs this extension in the remote workspace as well. And currently, since `extensionKind` doesn't contain `workspace`, this extension isn't available on the remote machine. Is that correct?

So in my opinion it's really a bug, but it seems that Metals is validated on remote, where scala-syntax is not enabled as it's installed locally, so since the last version VS Code will disable the extension. 

Haskell syntax doesn't declare the `extensionKind` at all and it all seems to work well.

**Review by MaximeKjaer — APPROVED** [review]
I see, thank you for the explanation @tgodzik ! Let's get this merged and release a new version.

**Comment by tgodzik** [comment]
> I see, thank you for the explanation @tgodzik ! Let's get this merged and release a new version.

Thanks!

**Pull request merged**
