### PR TITLE
Stop auto closing single quotes

### PR DESCRIPTION
**Pull request by Jentsch**
See https://github.com/scala/vscode-scala-syntax/issues/255#issuecomment-2399436847. Feel free to close this PR if I'm wrong.

Fixes Autoclosing Single Quote in Macro Programming #255

### CODE REVIEW

**Comment by tgodzik** [comment]
That is a bit of a conundrum, since want single to autoclose, but ideally after typing a single character :thinking: 

Though I agree this can be more annoying than helpful

**Comment by Jentsch** [comment]
For that we would need some kind of regular expression - something along the lines of `["'[^{]", "'"]`.
I couldn't find detailed specs for autoclosingpairs, but the implementation in vscode looks like it only supports strings. (But I found the code hard to read, I could be wrong here.) I also just tried, but to no avail.

**Review by tgodzik — APPROVED** [review]
Let's merge it since really this hasn't been a lot of help as you usually have to go back one character to actually write a character. `` itself is not valid

**Comment by Jentsch** [comment]
@tgodzik do we close now #255 or do we wait until the change is published?

**Comment by tgodzik** [comment]
We can close it yeah

**Pull request merged**
